[build]
  command = "npm run build"
  publish = "."
  functions = "functions"

[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200